name: CI
on: [push, pull_request]

jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                - uses: icepuma/rust-action@master
                  args: "cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test"


