name: Rust

on: [push]

jobs:
  build:
    name: Test ${{ matrix.buildArgs }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        buildArgs: ["","--features=sentry"]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: ${{ matrix.buildArgs }}
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: ${{ matrix.buildArgs }}
